version: "{build}"

os: unstable #http://help.appveyor.com/discussions/suggestions/427-pre-install-cygwin

platform:
    - Win32

clone_folder: C:/projects/haxe

environment:
    global:
        NEKO_ROOT: C:/projects/neko
        HAXELIB_ROOT: C:/projects/haxelib
        CYG_ARCH: x86
        CYG_ROOT: C:/cygwin
        CYG_SETUP: C:/cygwin/setup-x86.exe
        WODI_ARCH: 32
        MINGW_ARCH: i686
        TEST: "neko,cs,java,cpp,macro"

skip_tags: true

install:
    - 'git submodule update --init --recursive'
    # Install ocaml using wodi
    - appveyor DownloadFile "http://cygwin.com/setup-%CYG_ARCH%.exe" -FileName "%CYG_ROOT%\setup.exe"
    - '%CYG_ROOT%/setup.exe -q -R "%CYG_ROOT%" -P dos2unix -P diffutils -P cpio -P make -P patch -P mingw64-%MINGW_ARCH%-gcc-core -P mingw64-%MINGW_ARCH%-gcc-g++ > log.txt || type log.txt'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin" > log.txt || type log.txt'
    - '%CYG_ROOT%/bin/bash -lc "wget -q http://ml.ignorelist.com/wodi/8/wodi%WODI_ARCH%.tar.xz -O /tmp/wodi%WODI_ARCH%.tar.xz" > log.txt || type log.txt'
    - '%CYG_ROOT%/bin/bash -lc "cd /tmp && rm -rf wodi%WODI_ARCH% && tar -xf wodi%WODI_ARCH%.tar.xz && bash wodi%WODI_ARCH%/install.sh" > log.txt || type log.txt'
    - '%CYG_ROOT%/bin/bash -lc "godi_add godi-zip" > log.txt || type log.txt'
    - 'set PATH=%PATH%;%CYG_ROOT%/opt/wodi%WODI_ARCH%/bin'
    # Install neko
    - cinst make -y
    - 'git clone --recursive https://github.com/HaxeFoundation/neko.git %NEKO_ROOT%'
    - 'cd %NEKO_ROOT%'
    - set PATH=%PATH%;%NEKO_ROOT%/bin
    - msbuild neko_vc10.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" > log.txt || type log.txt
    - msbuild libs/libs_vc10.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" > log.txt || type log.txt
    - copy /y libs\include\gc\gc.dll bin
    - cd %NEKO_ROOT%/src
    - neko ../boot/nekoc tools/install.neko
    - neko tools/install -nolibs > log.txt || type log.txt
    - neko -version

build_script:
    - 'cd %APPVEYOR_BUILD_FOLDER%'
    - 'set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%'
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && make -s -f Makefile.win WODI=wodi%WODI_ARCH% OCAMLOPT=ocamlopt.opt"'
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && make -s -f Makefile.win WODI=wodi%WODI_ARCH% OCAMLOPT=ocamlopt.opt tools"'
    - cd %APPVEYOR_BUILD_FOLDER%/tests/
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%/tests/
    - haxe -version
    - haxe RunCi.hxml
    - neko RunCi.n
